document.write('<script src="/meter/resources/js/commonjs/datetimepicker/bootstrap-datetimepicker.min.js"></script>')
document.write('<script src="/meter/resources/js/commonjs/datetimepicker/locales/bootstrap-datetimepicker.zh-CN.js"></script>')
document.write('<script src="/meter/resources/js/commonjs/jquery-ui.min.js"></script>')
document.write('<script src="/meter/resources/js/commonjs/jquery.flot.js"></script>')
document.write('<script src="/meter/resources/js/page/camerasetting.js"></script>')
